from datetime import datetime, timezone, timedelta, date as date_type
from typing import Optional
from fastapi import APIRouter, Depends, Query, Response
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, and_
import io

from app.db.session import get_db
from app.core.deps import get_current_user
from app.core.entitlements import require_feature
from app.core.features import FeatureCode
from app.models.user import User, UserProfile, BodyMetric
from app.models.health import SleepSession, HydrationLog
from app.models.metrics import DailyMetrics

reports_router = APIRouter(prefix="/reports", tags=["Reports"])


def _make_pdf(user: User, profile: Optional[UserProfile], data: dict) -> bytes:
    """Genere un PDF sante simple avec fpdf2."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise RuntimeError("fpdf2 not installed. Run: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_fill_color(30, 30, 60)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 14, "SOMA Health Report", fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(2)

    # Metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    name = getattr(profile, "first_name", None) or user.username
    pdf.cell(0, 6, f"Patient : {name}   |   Period : {data["period_label"]}   |   Generated : {datetime.utcnow().strftime('%Y-%m-%d')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    def section(title: str):
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 60)
        pdf.set_fill_color(230, 235, 255)
        pdf.cell(0, 9, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "", 11)
        pdf.ln(2)

    def row(label: str, value: str):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(70, 7, label + " :")
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")

    # Body composition
    section("Body Composition")
    bm = data.get("latest_body_metric")
    if bm:
        if bm.get("weight_kg"):
            row("Weight", f"{bm['weight_kg']:.1f} kg")
        if bm.get("body_fat_pct"):
            row("Body fat", f"{bm['body_fat_pct']:.1f} %")
        if bm.get("muscle_mass_kg"):
            row("Muscle mass", f"{bm['muscle_mass_kg']:.1f} kg")
        if bm.get("bmi"):
            row("BMI", f"{bm['bmi']:.1f}")
    else:
        pdf.cell(0, 7, "No body composition data available.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Sleep
    section("Sleep")
    sleep = data.get("sleep_avg")
    if sleep:
        row("Avg duration", f"{sleep.get('avg_duration_min', 0):.0f} min")
        row("Sessions", str(sleep.get("count", 0)))
    else:
        pdf.cell(0, 7, "No sleep data available.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Hydration
    section("Hydration")
    hydration = data.get("hydration_avg")
    if hydration:
        row("Avg daily intake", f"{hydration.get('avg_ml', 0):.0f} ml")
        row("Days logged", str(hydration.get("days_logged", 0)))
    else:
        pdf.cell(0, 7, "No hydration data available.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Activity
    section("Activity")
    activity = data.get("activity_avg")
    if activity:
        row("Avg daily steps", f"{activity.get('avg_steps', 0):.0f}")
        row("Avg active cal", f"{activity.get('avg_active_cal', 0):.0f} kcal")
    else:
        pdf.cell(0, 7, "No activity data available.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Footer
    pdf.set_y(-18)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by SOMA Health Intelligence - for informational purposes only.", align="C")

    return bytes(pdf.output())

@reports_router.get("/health")
async def generate_health_report(
    period: str = Query("last_month", description="last_month | last_quarter | last_week"),
    current_user: User = Depends(require_feature(FeatureCode.PDF_REPORTS)),
    db: AsyncSession = Depends(get_db),
):
    """Genere et retourne un rapport PDF de sante pour la periode choisie."""
    now = datetime.now(timezone.utc)
    if period == "last_week":
        since = now - timedelta(days=7)
        period_label = "Last 7 days"
    elif period == "last_quarter":
        since = now - timedelta(days=90)
        period_label = "Last 90 days"
    else:
        since = now - timedelta(days=30)
        period_label = "Last 30 days"

    # Profil
    prof_result = await db.execute(select(UserProfile).where(UserProfile.user_id == current_user.id))
    profile = prof_result.scalar_one_or_none()

    # Derniere mesure corporelle
    bm_result = await db.execute(
        select(BodyMetric)
        .where(and_(BodyMetric.user_id == current_user.id, BodyMetric.measured_at >= since))
        .order_by(BodyMetric.measured_at.desc())
        .limit(1)
    )
    latest_bm = bm_result.scalar_one_or_none()
    bmi = None
    if latest_bm and latest_bm.weight_kg and profile and profile.height_cm:
        h = profile.height_cm / 100
        bmi = round(latest_bm.weight_kg / (h * h), 1)

    latest_body = None
    if latest_bm:
        latest_body = {
            "weight_kg": latest_bm.weight_kg,
            "body_fat_pct": latest_bm.body_fat_pct,
            "muscle_mass_kg": latest_bm.muscle_mass_kg,
            "bmi": bmi,
        }

    # Sommeil moyen
    sleep_result = await db.execute(
        select(
            func.count(SleepSession.id).label("count"),
            func.avg(SleepSession.duration_minutes).label("avg_duration_min"),
        ).where(and_(
            SleepSession.user_id == current_user.id,
            SleepSession.start_at >= since,
        ))
    )
    sleep_row = sleep_result.one_or_none()
    sleep_avg = {"count": sleep_row.count, "avg_duration_min": sleep_row.avg_duration_min or 0} if sleep_row and sleep_row.count else None

    # Hydratation moyenne
    hydration_result = await db.execute(
        select(
            func.count(func.distinct(func.date(HydrationLog.logged_at))).label("days_logged"),
            func.avg(HydrationLog.volume_ml).label("avg_ml"),
        ).where(and_(
            HydrationLog.user_id == current_user.id,
            HydrationLog.logged_at >= since,
        ))
    )
    hyd_row = hydration_result.one_or_none()
    hydration_avg = {"days_logged": hyd_row.days_logged, "avg_ml": hyd_row.avg_ml or 0} if hyd_row and hyd_row.days_logged else None

    # Activite depuis DailyMetrics
    act_result = await db.execute(
        select(
            func.avg(DailyMetrics.steps).label("avg_steps"),
            func.avg(DailyMetrics.active_calories_kcal).label("avg_active_cal"),
        ).where(and_(
            DailyMetrics.user_id == current_user.id,
            DailyMetrics.metrics_date >= since.date(),
        ))
    )
    act_row = act_result.one_or_none()
    activity_avg = {"avg_steps": act_row.avg_steps or 0, "avg_active_cal": act_row.avg_active_cal or 0} if act_row else None

    data = {
        "period_label": period_label,
        "latest_body_metric": latest_body,
        "sleep_avg": sleep_avg,
        "hydration_avg": hydration_avg,
        "activity_avg": activity_avg,
    }

    pdf_bytes = _make_pdf(current_user, profile, data)

    filename = f"soma_health_report_{period}_{datetime.utcnow().strftime('%Y%m%d')}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )